apiVersion: v1
kind: PersistentVolume
metadata:
  name: acceleration-calc
  namespace: desafio
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes: 
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/acc